# Generated by Django 4.2.5 on 2023-10-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40, verbose_name='Phone')),
                ('website', models.CharField(max_length=80, verbose_name='Website')),
                ('company', models.CharField(max_length=80, verbose_name='Company')),
            ],
        ),
    ]
